#!/usr/bin/env python3
"""Generate site artdefacts from the collodion wet plate ontology.

Dependency-free: this parses the controlled Turtle subset used by
``data/collodion-wetplate-ontology.ttl`` (no blank nodes, collections or
numeric literals) and emits:

  * ``data/ontology.jsonld``        — schema.org JSON-LD (DefinedTermSet + HowTo)
  * ``data/glossary.generated.html``— a glossary fragment in the site's markup
  * injects the JSON-LD into ``knowledge.html`` between marker comments.

The website stays a static, dependency-free mockup: only the build step runs
this script, and its outputs are committed. Re-run after editing the ontology:

    python3 tools/build_from_ontology.py
"""
from __future__ import annotations

import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTL = os.path.join(ROOT, "data", "collodion-wetplate-ontology.ttl")
JSONLD = os.path.join(ROOT, "data", "ontology.jsonld")
GLOSSARY = os.path.join(ROOT, "data", "glossary.generated.html")
KNOWLEDGE = os.path.join(ROOT, "knowledge.html")

JSONLD_START = "<!-- ONTOLOGY:JSONLD:START (generated by tools/build_from_ontology.py) -->"
JSONLD_END = "<!-- ONTOLOGY:JSONLD:END -->"

META_TYPES = {
    "owl:Class", "owl:Ontology", "owl:ObjectProperty", "owl:DatatypeProperty",
    "owl:TransitiveProperty", "owl:SymmetricProperty",
}


# --------------------------------------------------------------------------- #
# Minimal Turtle tokenizer + parser for the controlled subset we author.
# --------------------------------------------------------------------------- #
def tokenize(text):
    tokens, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c in " \t\r\n":
            i += 1
        elif c == "#":
            while i < n and text[i] != "\n":
                i += 1
        elif c == "<":
            j = text.index(">", i)
            tokens.append(("iri", text[i + 1:j]))
            i = j + 1
        elif c == '"':
            j, buf = i + 1, []
            while j < n and text[j] != '"':
                if text[j] == "\\":
                    buf.append(text[j + 1])
                    j += 2
                else:
                    buf.append(text[j])
                    j += 1
            val, j = "".join(buf), j + 1
            lang = None
            if j < n and text[j] == "@":
                k = j + 1
                while k < n and (text[k].isalnum() or text[k] == "-"):
                    k += 1
                lang, j = text[j + 1:k], k
            elif j + 1 < n and text[j:j + 2] == "^^":
                j += 2
                if text[j] == "<":
                    j = text.index(">", j) + 1
                else:
                    k = j
                    while k < n and text[k] not in " \t\r\n;,.":
                        k += 1
                    j = k
            tokens.append(("lit", val, lang))
            i = j
        elif c in ";,.()[]":
            tokens.append(("punct", c))
            i += 1
        elif c == "@":
            k = i + 1
            while k < n and text[k] not in " \t\r\n":
                k += 1
            tokens.append(("dir", text[i:k]))
            i = k
        else:
            k = i
            while k < n and text[k] not in ' \t\r\n;,.()[]<"#':
                k += 1
            tokens.append(("name", text[i:k]))
            i = k
    return tokens


def parse(tokens):
    """Return (triples, prefixes). triples = list of (subj, pred, obj).

    Resources are kept as CURIE/IRI strings; literals as ('lit', value, lang).
    """
    prefixes, triples, i, n = {}, [], 0, len(tokens)

    def obj_of(tok):
        if tok[0] == "iri":
            return tok[1]
        if tok[0] == "name":
            return tok[1]
        return ("lit", tok[1], tok[2])

    while i < n:
        tok = tokens[i]
        if tok[0] == "dir" and tok[1] == "@prefix":
            prefixes[tokens[i + 1][1].rstrip(":")] = tokens[i + 2][1]
            i += 3
            if i < n and tokens[i] == ("punct", "."):
                i += 1
            continue
        subj = tok[1]
        i += 1
        while True:
            pt = tokens[i]
            pred = "rdf:type" if (pt[0] == "name" and pt[1] == "a") else pt[1]
            i += 1
            while True:
                triples.append((subj, pred, obj_of(tokens[i])))
                i += 1
                if tokens[i] == ("punct", ","):
                    i += 1
                    continue
                break
            if tokens[i] == ("punct", ";"):
                i += 1
                if tokens[i] == ("punct", "."):
                    i += 1
                    break
                continue
            if tokens[i] == ("punct", "."):
                i += 1
                break
    return triples, prefixes


# --------------------------------------------------------------------------- #
# Indexing helpers
# --------------------------------------------------------------------------- #
def build_index(triples):
    idx = {}
    for s, p, o in triples:
        idx.setdefault(s, {}).setdefault(p, []).append(o)
    return idx


def literals(values, lang=None):
    out = []
    for v in values or []:
        if isinstance(v, tuple) and v[0] == "lit":
            if lang is None or v[2] == lang:
                out.append(v[1])
    return out


def label(idx, subj, lang="en"):
    labels = idx.get(subj, {}).get("rdfs:label", [])
    return (literals(labels, lang) or literals(labels, "nl") or literals(labels)
            or [subj.split(":")[-1]])[0]


def definition(idx, subj, lang="en"):
    defs = idx.get(subj, {}).get("skos:definition", [])
    vals = literals(defs, lang) or literals(defs)
    return vals[0] if vals else ""


def see_also(idx, subj):
    for o in idx.get(subj, {}).get("rdfs:seeAlso", []):
        if isinstance(o, str) and o.startswith("http"):
            return o
    return ""


def alt_labels(idx, subj, lang="en"):
    return literals(idx.get(subj, {}).get("skos:altLabel", []), lang)


def types(idx, subj):
    return [t for t in idx.get(subj, {}).get("rdf:type", []) if isinstance(t, str)]


def is_individual(idx, subj):
    ts = types(idx, subj)
    return ts and all(t not in META_TYPES for t in ts) and any(t.startswith("cwp:") for t in ts)


def full_iri(curie, prefixes):
    pfx, _, local = curie.partition(":")
    return prefixes.get(pfx, pfx + ":") + local


# --------------------------------------------------------------------------- #
# Ordering of process steps via the precedes chain
# --------------------------------------------------------------------------- #
def ordered_steps(idx, process):
    steps = [s for s in idx.get(process, {}).get("cwp:hasStep", []) if isinstance(s, str)]
    if not steps:
        return []
    succ = {}
    for s in steps:
        nxt = [x for x in idx.get(s, {}).get("cwp:precedes", []) if isinstance(x, str)]
        if nxt:
            succ[s] = nxt[0]
    has_pred = set(succ.values())
    start = next((s for s in steps if s not in has_pred), steps[0])
    chain, seen, cur = [], set(), start
    while cur and cur not in seen:
        chain.append(cur)
        seen.add(cur)
        cur = succ.get(cur)
    for s in steps:  # append any not reached by the chain
        if s not in seen:
            chain.append(s)
    return chain


# --------------------------------------------------------------------------- #
# Generators
# --------------------------------------------------------------------------- #
def make_jsonld(idx, prefixes):
    terms = sorted((s for s in idx if is_individual(idx, s) and definition(idx, s)),
                   key=lambda s: label(idx, s).lower())
    term_set_id = full_iri("cwp:CollodionWetplateOntology", prefixes) + "/glossary"
    defined_terms = []
    for s in terms:
        node = {
            "@type": "DefinedTerm",
            "@id": full_iri(s, prefixes),
            "name": label(idx, s),
            "description": definition(idx, s),
            "inDefinedTermSet": term_set_id,
        }
        alts = alt_labels(idx, s)
        if alts:
            node["alternateName"] = alts if len(alts) > 1 else alts[0]
        if see_also(idx, s):
            node["url"] = see_also(idx, s)
        defined_terms.append(node)

    graph = [{
        "@type": "DefinedTermSet",
        "@id": term_set_id,
        "name": "Wet plate collodion glossary",
        "hasDefinedTerm": defined_terms,
    }]

    proc = "cwp:WetPlateCollodionProcess"
    if proc in idx:
        steps = ordered_steps(idx, proc)
        howto = {
            "@type": "HowTo",
            "@id": full_iri(proc, prefixes),
            "name": label(idx, proc),
            "description": definition(idx, proc),
            "step": [{
                "@type": "HowToStep",
                "position": i + 1,
                "name": label(idx, s),
                "text": definition(idx, s) or label(idx, s),
            } for i, s in enumerate(steps)],
        }
        if see_also(idx, proc):
            howto["url"] = see_also(idx, proc)
        graph.append(howto)

    return {"@context": "https://schema.org", "@graph": graph}


def make_glossary_html(idx, prefixes):
    terms = sorted((s for s in idx if is_individual(idx, s) and definition(idx, s)),
                   key=lambda s: label(idx, s).lower())
    rows = [
        '<!-- Generated by tools/build_from_ontology.py from '
        'data/collodion-wetplate-ontology.ttl — do not edit by hand. -->',
        '<div class="cat-list" data-generated="ontology">',
    ]
    for s in terms:
        name = html.escape(label(idx, s))
        desc = html.escape(definition(idx, s))
        alts = alt_labels(idx, s)
        alt = (' <span class="muted">(' + html.escape(", ".join(alts)) + ")</span>") if alts else ""
        url = see_also(idx, s)
        if url:
            cite = (f'<span class="src-label">Source:</span>'
                    f'<span class="badge badge--book">Reference</span>'
                    f'<a href="{html.escape(url)}" target="_blank" rel="noopener">'
                    f'{name} — overview &amp; citations ↗</a>')
        else:
            cite = ('<span class="src-label">Source:</span>'
                    '<span class="badge badge--book">Ontology</span>'
                    '<span>Wetplate Hub structured vocabulary</span>')
        rows += [
            '  <div class="cat">',
            '    <div class="ico">\U0001F4D6</div>',
            '    <div class="cat-text">',
            f"      <h3>{name}{alt}</h3>",
            f"      <p>{desc}</p>",
            f'      <div class="cite">{cite}</div>',
            "    </div>",
            "  </div>",
        ]
    rows.append("</div>")
    return "\n".join(rows) + "\n"


def inject_jsonld(jsonld):
    block = (JSONLD_START + "\n"
             + '  <script type="application/ld+json">\n'
             + json.dumps(jsonld, indent=2, ensure_ascii=False) + "\n"
             + "  </script>\n  " + JSONLD_END)
    with open(KNOWLEDGE, encoding="utf-8") as fh:
        page = fh.read()
    if JSONLD_START in page and JSONLD_END in page:
        pre = page[:page.index(JSONLD_START)]
        post = page[page.index(JSONLD_END) + len(JSONLD_END):]
        page = pre + block + post
    else:
        page = page.replace("</head>", "  " + block + "\n</head>", 1)
    with open(KNOWLEDGE, "w", encoding="utf-8") as fh:
        fh.write(page)


def main():
    with open(TTL, encoding="utf-8") as fh:
        triples, prefixes = parse(tokenize(fh.read()))
    idx = build_index(triples)

    jsonld = make_jsonld(idx, prefixes)
    with open(JSONLD, "w", encoding="utf-8") as fh:
        json.dump(jsonld, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    with open(GLOSSARY, "w", encoding="utf-8") as fh:
        fh.write(make_glossary_html(idx, prefixes))
    inject_jsonld(jsonld)

    n_terms = len(jsonld["@graph"][0]["hasDefinedTerm"])
    n_steps = len(jsonld["@graph"][1]["step"]) if len(jsonld["@graph"]) > 1 else 0
    print(f"Parsed {len(triples)} triples, {len(idx)} subjects.")
    print(f"Wrote {os.path.relpath(JSONLD, ROOT)} "
          f"({n_terms} glossary terms, {n_steps} HowTo steps).")
    print(f"Wrote {os.path.relpath(GLOSSARY, ROOT)}.")
    print(f"Injected JSON-LD into {os.path.relpath(KNOWLEDGE, ROOT)}.")


if __name__ == "__main__":
    main()
